/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Myclass */

#ifndef _Included_Myclass
#define _Included_Myclass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Myclass
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Myclass_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     Myclass
 * Method:    isPalindrome
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Myclass_isPalindrome
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Myclass
 * Method:    accessDetails
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Myclass_accessDetails
  (JNIEnv *, jobject);

/*
 * Class:     Myclass
 * Method:    modifyDetails
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Myclass_modifyDetails
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
