/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Myclass */

#ifndef _Included_Myclass
#define _Included_Myclass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Myclass
 * Method:    accessDetails
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Myclass_accessDetails
  (JNIEnv *, jobject);

/*
 * Class:     Myclass
 * Method:    modifyDetails
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Myclass_modifyDetails
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
