/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Palindrome */

#ifndef _Included_Palindrome
#define _Included_Palindrome
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Palindrome
 * Method:    isPalindrome
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Palindrome_isPalindrome
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
