/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ThrowCatch */

#ifndef _Included_ThrowCatch
#define _Included_ThrowCatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ThrowCatch
 * Method:    catchThrow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ThrowCatch_catchThrow
  (JNIEnv *, jobject);

/*
 * Class:     ThrowCatch
 * Method:    catchThrow1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ThrowCatch_catchThrow1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
